# NUMPY(Numerical Python)

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy,logical and mathematical operations,fourier transforms and routines for shape manipulation,operations related to linear algebra can be performed.
Also,NumPy has in-built functions for linear algebra and random number generationon arrays are performed.

In this file we will discusses the various array functions, types of indexing, etc. All this is explained with the help of examples for better understanding.

# WHY NUMPY

In [1]:
#Importing
import numpy as np

In [2]:
# NP VERSION
print(np.__version__)

1.16.2


In [3]:
#Creating One dimensional array
a = np.array([1,2,3])
print("ARRAY",a)
print("SHAPE",a.shape) 
print("TYPE",a.dtype)
print("DIMENSION",a.ndim)

ARRAY [1 2 3]
SHAPE (3,)
TYPE int32
DIMENSION 1


In [4]:
#Creating Two dimensional array
b = np.array([[1,2,3],[4,5,6]])
print("ARRAY",b)
print("SHAPE",b.shape) 
print("TYPE",b.dtype)
print("DIMENSION",b.ndim)

ARRAY [[1 2 3]
 [4 5 6]]
SHAPE (2, 3)
TYPE int32
DIMENSION 2


# Performance

In [5]:
c = range(10000)
%timeit [i**3 for i in c]

3.73 ms ± 49.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]
%timeit list(map(lambda x, y: x*y, l1, l2))

1.22 ms ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
a1 = np.array(l1)
b1 = np.array(l2)

In [8]:
%timeit a1*b1

8.82 µs ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# There are multiple ways to create numpy array

In [9]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [11]:
#Creating a single dimensional array with zeros and replacing 4th index with 1
z=np.zeros(10)
print(z)
z[4]=1
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
# create a 5x5 array of zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# create a 3x2 array of ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
#Creating array where only diagnal elements are 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Creating a 3x3 array where all values are 2
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
#Creating a matrix with diagnal elements are manually given
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [17]:
#Other way
z=np.diag(1+np.arange(4))
z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
z=np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
# FIND THE INDICIES OF NON ZERO ELEMENTS
z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [20]:
import random

In [21]:
# Generating 100 random numbers between 0 and 1
z=np.random.random((10,10))
z

array([[0.00770605, 0.96032822, 0.04475557, 0.17438558, 0.75214655,
        0.41418823, 0.00534146, 0.01030778, 0.51403086, 0.76327917],
       [0.5960557 , 0.50665729, 0.06764912, 0.45781085, 0.41850592,
        0.11696456, 0.54664083, 0.24716575, 0.89680511, 0.56847677],
       [0.371147  , 0.90509024, 0.71533838, 0.55229265, 0.95827526,
        0.7082059 , 0.13408391, 0.4678182 , 0.7090198 , 0.43609305],
       [0.23061117, 0.36083193, 0.76954888, 0.17352925, 0.37586585,
        0.17402914, 0.97112385, 0.83466193, 0.24621909, 0.66640109],
       [0.91919591, 0.45046622, 0.89091981, 0.79921107, 0.38777983,
        0.6847966 , 0.86267288, 0.24999693, 0.61449248, 0.45415028],
       [0.13242383, 0.03750146, 0.33788557, 0.60246844, 0.05312952,
        0.1829975 , 0.06734272, 0.64128855, 0.26745999, 0.86756334],
       [0.58333288, 0.49121176, 0.85451371, 0.94021396, 0.68821538,
        0.9086794 , 0.37259292, 0.98202258, 0.70194113, 0.44788782],
       [0.98734394, 0.35359424, 0.7054454

In [22]:
np.random.seed(101)
np.random.random([3,3])

array([[0.51639863, 0.57066759, 0.02847423],
       [0.17152166, 0.68527698, 0.83389686],
       [0.30696622, 0.89361308, 0.72154386]])

In [23]:
#Random integer b/w 5 and 20
np.random.randint(5,20)


5

In [24]:
#Random 10 integers b/w 5 and 20
np.random.randint(5,20,10)

array([19, 10, 17, 18, 13,  6,  8, 15, 13,  8])

In [25]:
# 100 values between 1 and 50 at equal spaces
a = np.linspace(1,50,100)
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [26]:
z=np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
z[[0,-1],[0,-1]]=0
z

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [28]:
z=np.zeros((8,8),dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
z[1::2,0::2]=1
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [30]:
z=np.zeros((8,8),dtype=int)

z[::2,1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
list1=[11,22,33,44,55]
arr1=np.array(list1)

In [32]:
arr1.itemsize
#4 bytes memory

4

In [33]:
arr1.size

5

In [34]:
print("Total memory accupied :{}".format(arr1.size*arr1.itemsize))

Total memory accupied :20


In [35]:
np.arange(18).reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [36]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# Mathematical operations

In [37]:
a = np.arange(1,10)

In [38]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [39]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [40]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [41]:
np.sum(a)

45

In [42]:
np.median(a)

5.0

In [43]:
a.std()

2.581988897471611

In [44]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)



In [45]:
np.logical_or(a,b)

array([ True,  True,  True])

In [46]:
np.logical_and(a,b)

array([ True, False, False])

In [47]:
np.all(a == a)

True

# Extraction(2-d array)

In [48]:
a86=np.arange(48).reshape(8,6)
print(a86)
a86[2],[4]

v4=a86[3:6,1:5:2]
v4

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


array([[19, 21],
       [25, 27],
       [31, 33]])

In [49]:
v3=a86[3:]
print(v3)
print(v3.shape)

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
(5, 6)


In [50]:
v4=a86[3:6,4]
print(v4)


[22 28 34]


In [51]:
v4=a86[3:6,1:5:2]
print(v4)
print(type(v4))

[[19 21]
 [25 27]
 [31 33]]
<class 'numpy.ndarray'>


In [52]:
v5=a86[4:7:2,1:5:3]
v5

array([[25, 28],
       [37, 40]])

# Extraction(3-d array)

In [53]:
# 5 rows 4 columns 3 is depth
a=np.arange(1,61).reshape(5,4,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]

 [[49 50 51]
  [52 53 54]
  [55 56 57]
  [58 59 60]]]


In [54]:
print(a[2][2][1])
print(a[3][1][0])
print(a[1][0][2])

32
40
15


In [55]:
v1=a[1:3,[0,2],1]
v1

array([[14, 20],
       [26, 32]])

In [56]:
v2=a[[3,2],[2,1],[1,0]]
v2

array([44, 28])

# SCALAR/VECTOR broadcasts

In [57]:
# ROW ADDITION
a=np.arange(1,25,dtype=np.int32).reshape(6,4)

b=np.arange(1,5,dtype=np.int32).reshape(1,4)

print(a)
print("######################################")
print(b)
c=a+b
print("##########################################")
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
######################################
[[1 2 3 4]]
##########################################
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]
 [18 20 22 24]
 [22 24 26 28]]


In [58]:
# COLUMN ADDITION
a=np.arange(1,25,dtype=np.int32).reshape(6,4)

b=np.arange(1,7,dtype=np.int32).reshape(6,1)

print(a)
print("######################################")
print(b)
c=a+b
print("##########################################")
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
######################################
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
##########################################
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]
 [27 28 29 30]]


# H-SPLIT

In [59]:
import numpy as np
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [60]:
print(np.hsplit(x,2))
print("#######################")

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
#######################


# V-SPLIT

In [61]:
import numpy as np
x=np.arange(16).reshape(4,4)
print(x)

print(np.vsplit(x,2))

y=np.array([0,1])
print(y)
x=np.vsplit(x,y)
print(x)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[0 1]
[array([], shape=(0, 4), dtype=int32), array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# STACKING

In [62]:
#ADDING COLUMNS

In [63]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)
print("###########")
y=np.arange(3).reshape(3,1)
print(y)
print("###########")

z=np.hstack((x,y))
print(z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
###########
[[0]
 [1]
 [2]]
###########
[[0 1 2 0]
 [3 4 5 1]
 [6 7 8 2]]


In [64]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)
print("###########")
y=np.arange(3).reshape(1,3)
print(y)
print("###########")
z=np.vstack((x,y))
print(z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
###########
[[0 1 2]]
###########
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]


# Conditional Acess

In [65]:
def create_np_array(r=3,c=4,d=2):
    x=np.random.randint(25,size=(r,c,d))
    return x


In [66]:
z=create_np_array(4,5,3)
print(z)
print(z.shape)

[[[19  2 12]
  [ 8 19 10]
  [12 11 23]
  [ 0  9 23]
  [ 9 15  8]]

 [[ 4 19  3]
  [ 7 10 20]
  [24  7  6]
  [14  9 20]
  [18 23  7]]

 [[ 7 15 12]
  [ 0 20 10]
  [12 17 24]
  [11 19 15]
  [ 1 24  4]]

 [[19 18  3]
  [10 19  7]
  [20  8 22]
  [19 23 14]
  [15 22  5]]]
(4, 5, 3)


In [67]:
y=z>15
print(y)
print(y.shape)


[[[ True False False]
  [False  True False]
  [False False  True]
  [False False  True]
  [False False False]]

 [[False  True False]
  [False False  True]
  [ True False False]
  [False False  True]
  [ True  True False]]

 [[False False False]
  [False  True False]
  [False  True  True]
  [False  True False]
  [False  True False]]

 [[ True  True False]
  [False  True False]
  [ True False  True]
  [ True  True False]
  [False  True False]]]
(4, 5, 3)


In [68]:
x=z[y]
print(x)
print(type(x))

[19 19 23 23 19 20 24 20 18 23 20 17 24 19 24 19 18 19 20 22 19 23 22]
<class 'numpy.ndarray'>
